@ cdecl pt3_open(long)
@ cdecl pt1_open(long)
@ cdecl ptx_open_device(str)
@ cdecl ptx_close_device(long)
@ cdecl ptx_select(long long)
@ cdecl ptx_read(long str long)
@ cdecl ptx_purge(long)
@ cdecl ptx_tune(long str)
@ cdecl ptx_getlevel_t(long)
@ cdecl ptx_getlevel_s(long)
@ cdecl ptx_start(long)
@ cdecl ptx_stop(long)
