@ cdecl pt3_open(long)
@ cdecl pt1_open(long)
#@ cdecl ptx_open_device(str)
#@ cdecl ptx_close_device(long)
@ cdecl ptx_select(str long)
@ cdecl ptx_read(str str long)
@ cdecl ptx_purge(str)
@ cdecl ptx_tune(str str)
@ cdecl ptx_getlevel_t(str)
@ cdecl ptx_getlevel_s(str)
@ cdecl ptx_start(str)
@ cdecl ptx_stop(str)
